#!/bin/sh
# -*- sh -*-

. `dirname $0`/tc7200_common
router_login

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then
        echo 'graph_title Downstream channels frequencies'
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel MHz'
        echo 'graph_category upc'
        echo 'graph_info The frequencies of the cable modems downstream channels.'
	wget -q -O - http://$routerip/status/connection-downstream.asp|grep QAM |sed -e 's/<td>//g' -e 's,</tr>,,' | awk -F '</td>' '{print "channel" $2 ".label channel " $2 "\nchannel" $2 ".draw LINE2\nchannel" $2 ".info Frequency for downstream channel " $2 " in MHz" }'
        exit 0
fi

wget -q -O - http://$routerip/status/connection-downstream.asp|grep QAM |sed -e 's/<td>//g' -e 's,</tr>,,' | awk -F '</td>' '{print "channelid" $2 ".value " $4/1000000}'

router_logout
